#!/bin/bash

APP_HOME=`pwd`

option=$1
pattern=$2
base=$3

help() {
	echo -e '\nTo start the application, run: coletor_de_dados [-options] patternFilePath baseTextFilePath\n'
	echo -e 'Algorithms :\n'
	echo -e '1: Brute Force'
	echo -e '2: Knuth-Morris-Prat'
	echo -e '3: Rabin-Karp\n'
	echo -e 'Select the corresponding number\n'
	exit 1

}

function run() {
	 if [ $option -eq 1 ] || [ $option -eq 2 ] || [ $option -eq 3 ]; then 
	 	OUT= java -jar MCStringSearcher.jar $option $pattern $base
		echo -e $OUT
	 else help
            exit 1
    fi
}


run



