#!/bin/bash

APP_HOME=`pwd`
algorithms=(1 2 3)
patterns=('exp1.txt' 'exp2.txt' 'exp3.txt' 'exp4.txt')
baseFiles=( 'googlebooks-eng-all-1gram-20120701-9' 'googlebooks-eng-all-1gram-20120701-2')

function runExperiment(){
	echo "TextoBuscado,TextoBusca,Algoritmo,Resultado,TempoDeExecucao,Memoria,Operacoes" >> results.csv

	
	for((i=1; i<6;i++))
	do
		for number in ${algorithms[@]};
		do
			for ((b=0;b<${#baseFiles[@]};b++));
			do
				for pattern in ${patterns[@]};
				do
					echo -e "running with algorithm $number pattern $pattern and base file$b ${baseFiles[$b]}"
					java -jar MCStringSearcher.jar $number "file$b/$pattern" ${baseFiles[$b]} >> results$i.csv
				done
			done

		done
	done

}

	 	 
runExperiment
