#!/bin/bash

APP_HOME=`pwd`
algorithms=(1 2 3)
patterns=('palavra4.txt' 'palavra2.txt' 'palavra1.txt' 'palavra3.txt')
baseFiles=( 'googlebooks-eng-all-1gram-20120701-9' 'googlebooks-eng-all-1gram-20120701-2')

function runExperiment(){
	echo "TextoBuscado,TextoBusca,Algoritmo,Resultado,TempoDeExecucao,Memoria,Operacoes" >> results.csv

	for number in ${algorithms[@]};
	do
		for base in ${baseFiles[@]};
		do
			for pattern in ${patterns[@]};
			do
				echo -e "running with algorith $number pattern $pattern and base file $base"
				java -jar MCStringSearcher.jar $number $pattern $base >> results.csv
			done
		done

	done

}


runExperiment